# Be sure to restart your server when you modify this file.
#
# This file eases the Rails 8.1 framework defaults upgrade.
#
# Uncomment each configuration one by one to switch to the new default. Once the
# app is ready to run with all new defaults, remove this file and set
# `config.load_defaults` to `8.1` in config/application.rb.
#
# Read the upgrade guide for more details:
# https://guides.rubyonrails.org/upgrading_ruby_on_rails.html

# Skip escaping HTML entities and line separators in JSON responses.
# Rails.configuration.action_controller.escape_json_responses = false

# Skip escaping LINE SEPARATOR and PARAGRAPH SEPARATOR in JSON.
# Rails.configuration.active_support.escape_js_separators_in_json = false

# Raise when order-dependent finder methods run without an order column.
# Rails.configuration.active_record.raise_on_missing_required_finder_order_columns = true

# Raise for path-relative redirects without a leading slash.
# Rails.configuration.action_controller.action_on_path_relative_redirect = :raise

# Use the Ruby parser to track dependencies between Action View templates.
# Rails.configuration.action_view.render_tracker = :ruby

# Omit autocomplete="off" on hidden form fields generated by Rails helpers.
# Rails.configuration.action_view.remove_hidden_field_autocomplete = true
